/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.13/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the application plugin to add support for building a CLI application in Java.
    application

    // Serializzazione per Kotlin (usa la stessa versione di Kotlin)
    kotlin("plugin.serialization") version "1.9.20"

    // Plugin per creare un jar eseguibile con tutte le dipendenze
    id("com.github.johnrengelman.shadow") version "8.1.1"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    google()  // Necessario per alcune dipendenze Android
}

val mcpVersion = "0.4.0"
val slf4jVersion = "2.0.9"
val ktorVersion = "3.1.1"
val coroutinesVersion = "1.7.3"

dependencies {
    // Use the Kotlin JUnit 5 integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // Coroutine test support (virtual time, TestCoroutineScheduler)
    testImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:$coroutinesVersion")

    // MockWebServer for HTTP client testing
    testImplementation("com.squareup.okhttp3:mockwebserver:4.12.0")

    // MockK for mocking dependencies in unit tests
    testImplementation("io.mockk:mockk:1.13.10")

    // Kotlin coroutines
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutinesVersion")
    implementation("org.jetbrains.kotlinx:kotlinx-io:0.1.16")



    // MCP SDK e dipendenze correlate
    implementation("io.modelcontextprotocol:kotlin-sdk:$mcpVersion")
    implementation("org.slf4j:slf4j-simple:$slf4jVersion")
    implementation("io.ktor:ktor-client-content-negotiation:$ktorVersion")
    implementation("io.ktor:ktor-serialization-kotlinx-json:$ktorVersion")

    // Adam - ADB client per Kotlin (sostituzione di adbkit)
    implementation("com.malinskiy.adam:adam:0.5.0")

    // Gson for JSON serialization
    implementation("com.google.code.gson:gson:2.10.1")

    // Clikt — CLI argument parsing for the `visiontest <subcommand>` surface.
    // Used only when the JAR is invoked with CLI args; MCP stdio path does not touch clikt.
    implementation("com.github.ajalt.clikt:clikt:4.4.0")

    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    // Define the main class for the application.
    mainClass = "com.example.visiontest.MainKt"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests. Exclude the "e2e" tag: those tests spawn
    // the assembled fat JAR as a subprocess and run via the dedicated `e2eTest` task.
    useJUnitPlatform {
        excludeTags("e2e")
    }
}

// End-to-end tests: build the shadow JAR, then run the "e2e"-tagged tests against
// the real `java -jar visiontest.jar ...` chain. Kept out of `test` so the pure-JVM
// unit suite stays fast and does not depend on assembling the fat JAR.
tasks.register<Test>("e2eTest") {
    description = "Runs end-to-end tests against the assembled shadow JAR."
    group = "verification"
    dependsOn(tasks.named("shadowJar"))
    shouldRunAfter(tasks.named("test"))

    testClassesDirs = sourceSets["test"].output.classesDirs
    classpath = sourceSets["test"].runtimeClasspath

    useJUnitPlatform {
        includeTags("e2e")
    }
    systemProperty(
        "visiontest.jar",
        layout.buildDirectory.file("libs/visiontest.jar").get().asFile.absolutePath,
    )
}

// Run e2e tests as part of `check` (and therefore `build` and CI). shadowJar is
// already in the `build` graph, so the only added cost is the subprocess runs —
// this is the gate that catches packaging regressions (e.g. the embedded
// instructions resource being dropped from the fat JAR). The fast `test` task is
// unaffected since it does not depend on `check`.
tasks.named("check") {
    dependsOn("e2eTest")
}

// Copy AGENT_INSTRUCTIONS.md from repo root into JAR resources so InitCommand can read it at runtime.
tasks.named<ProcessResources>("processResources") {
    from(rootProject.file("AGENT_INSTRUCTIONS.md")) {
        rename { "agent-instructions.md" }
    }
}

// Configurazione per il jar ombra (con tutte le dipendenze)
tasks {
    shadowJar {
        archiveBaseName.set("visiontest")
        archiveClassifier.set("")
        archiveVersion.set("")
    }
}