/*
 * This source file was generated by the Gradle 'init' task
 */
package com

import com.example.visiontest.Android
import kotlin.test.Test
import kotlin.test.assertNotNull
import kotlinx.coroutines.runBlocking

class AndroidTest {
    @Test fun androidCanListDevices(): Unit =  runBlocking {
        val android = Android()
        val apps = android.listDevice()
        assertNotNull(apps, "app should have a list of devices")
    }
}
